# Generated by Django 4.2.21 on 2025-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_customer_customer_name_customer_shop_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanvisit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='salesmanvisit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
