# Generated by Django 4.2.21 on 2025-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_salesmanvisit_latitude_salesmanvisit_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanvisit',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
